#!/bin/bash

# Comment out to use ENV vars in a pipeline
PIPELINE_LAMBDA_VERSION="2.0.0"
PIPELINE_LAMBDA_NAME="ec2-backup"
PIPELINE_LAMBDA_SOURCE="./lambda_src/"
PIPELINE_ARTIFACT_BUCKET="my-bucket-name"

ZIP_FILE=${PIPELINE_LAMBDA_NAME}-v${PIPELINE_LAMBDA_VERSION}.zip

zip -r ${ZIP_FILE} ${PIPELINE_LAMBDA_SOURCE}

aws s3 cp ${ZIP_FILE} s3://${PIPELINE_ARTIFACT_BUCKET}/${PIPELINE_LAMBDA_NAME}/${ZIP_FILE}
