name: Repo Governance

on: push

jobs:
  job1:
    name: Repo Governance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Audit Repository
        uses: zerodaysec/repo-audit-action@main #change to version
        with:
          files: README.md,CODEOWNERS
          actions: terraform-lint.yml,help-wanted.yml
